CV.Web/Controllers/EducacionController.cs
using CV.Entidades;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Net.Http.Formatting;
using log4net;

namespace CV.Web.Controllers
{
    public class EducacionController : Controller
    {

        private static readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Educacion").Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var listado = JsonConvert.DeserializeObject<List<EducacionDTO>>(resultString);
                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultado = listado.Where(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId).OrderByDescending(x => x.EducacionId);
                        return View(resultado);
                    }
                    else
                    {
                        return View(listado);
                    }
                }

                return View();
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        
        public ActionResult Nuevo()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                    return View();
            }
            catch(Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(EducacionDTO educacion)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PostAsync("api/Educacion", educacion, new JsonMediaTypeFormatter()).Result;

            try
            {

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                    return View(educacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View(educacion);
        }

        [HttpGet]
        public ActionResult Actualizar(int id)
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Educacion/" + id).Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<EducacionDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Actualizar(EducacionDTO educacion)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PutAsync("api/Educacion/", educacion, new JsonMediaTypeFormatter()).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.DeleteAsync("api/Educacion/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Detalle(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.GetAsync("api/Educacion/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<EducacionDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }
    }
}

CV.Web/Controllers/IdiomaController.cs
using CV.Entidades;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Net.Http.Formatting;
using log4net;

namespace CV.Web.Controllers
{
    public class IdiomaController : Controller
    {
        private static readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Idioma").Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var listado = JsonConvert.DeserializeObject<List<IdiomaDTO>>(resultString);
                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultado = listado.Where(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId).OrderByDescending(x => x.IdiomaId);
                        return View(resultado);
                    }
                    else
                    {
                        return View(listado);
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                return View();
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(IdiomaDTO idioma)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PostAsync("api/Idioma", idioma, new JsonMediaTypeFormatter()).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                    return View(idioma);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View(idioma);
        }

        [HttpGet]
        public ActionResult Actualizar(int id)
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Idioma/" + id).Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<IdiomaDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Actualizar(IdiomaDTO idioma)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PutAsync("api/Idioma/", idioma, new JsonMediaTypeFormatter()).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.DeleteAsync("api/Idioma/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Detalle(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.GetAsync("api/Idioma/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<IdiomaDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }
    }
}

CV.Web/Views/Idioma/Actualizar.cshtml
@model IdiomaDTO

<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-9 col-sm-9 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "Idioma")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
            </div>

            <h2>Editar Idioma</h2>

            <form method="post" action="@Url.Action("Actualizar", "Educacion")">
                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                @if (ViewBag.ObjUsuario != null)
                {
                    <input type="hidden" value="@ViewBag.ObjUsuario.UsuarioId" name="UsuarioId" />
                }
                @Html.HiddenFor(x => x.IdiomaId)
                <div class="col-sm-9 form-group">
                    <label for="Descripcion">Descripción: </label>
                    @Html.TextBoxFor(x => x.Descripcion, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(x => x.Descripcion)

                </div>
                <div class="col-sm-9 form-group">
                    <label for="NivelEscrito">Nivel Escrito:</label>
                    @Html.DropDownListFor(x => x.NivelEscrito, new SelectList(new string[] { "--- Selecionar Nivel ---", "Bajo", "Intermedio", "Alto" }), new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.NivelEscrito)
                </div>

                <div class="col-sm-9 form-group">
                    <label for="NivelOral">Nivel Oral:</label>
                    @Html.DropDownListFor(x => x.NivelOral, new SelectList(new string[] { "--- Selecionar Nivel ---", "Bajo", "Intermedio", "Alto" }), new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.NivelOral)
                </div>

                <div class="col-sm-6 form-group">
                    <button type="submit" class="btn btn-success btn-lg">Editar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="primary" />

CV.Web/Views/Idioma/Detalle.cshtml
@model IdiomaDTO

<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-12 col-sm-12 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "Idioma")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
                <a href="@Url.Action("Actualizar", "Idioma", new { id = Model.IdiomaId})"><p class="btn btn-outline-dark btn-lg text-uppercase"><i class="fa fa-edit"></i> Editar</p></a>
            </div>

            <div class="card col-lg-12 col-sm-12">
                <div class="card-header text-center">
                    <i class="fa fa fa-globe fa-2x"></i> Idioma: @Model.Descripcion
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><i class="fa fa-pencil fa-2x"></i> Nivel Escrito: @Model.NivelEscrito</li>
                    <li class="list-group-item"><i class="fa fa-comment fa-2x"></i> Nivel Oral: @Model.NivelOral</li>
                </ul>
            </div>
        </div>
    </div>
</div>

CV.Web/Views/Idioma/Index.cshtml
@model IEnumerable<IdiomaDTO>
@{
    ViewBag.Title = "Index";
}

<section id="two" class="bg-alt">

    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-xs-center">
                @if (ViewBag.ObjUsuario != null)
                {
                    <h2><span class="text-success">@ViewBag.ObjUsuario.UsuarioNombre</span> Continuemos completando el CV.</h2>
                }

                <h3 class="m-t-0 text-primary">Impulsá tu carrera profesional</h3>
                <a href="@Url.Action("Index", "ExperienciaLaboral")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
                <h4>Idiomas</h4>
                @if (Model != null)
                {
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Descripción</th>
                                <th>Ver</th>
                                <th>Editar</th>
                                <th>Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var datos in Model)
                            {
                                <tr>
                                    <td>@datos.Descripcion</td>
                                    <td><a href="@Url.Action("Detalle", "Idioma", new { id = datos.IdiomaId})"><i class="fa fa-eye fa-2x"></i></a></td>
                                    <td><a href="@Url.Action("Actualizar", "Idioma", new { id = datos.IdiomaId})"><i class="fa fa-edit fa-2x text-success"></i></a></td>
                                    <td style="cursor:pointer" id="eliminar" data-id="@datos.IdiomaId" data-Descripcion="@datos.Descripcion" data-toggle="modal" data-target="#eliminarIdioma"><i class="fa fa-trash fa-2x text-danger"></i></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <a href="@Url.Action("Nuevo", "Idioma")" class="btn btn-dark btn-xl page-scroll wow fadeInUp">Nuevo Item Idioma <i class="fa fa-globe"></i></a>
                    <a href="@Url.Action("Index", "Conocimiento")" class="btn btn-primary btn-xl page-scroll wow fadeInUp">Completar Conocimiento <i class="fa fa-user-plus"></i></a>
                }
                else
                {
                    <p class="text-capitalize">No hay idiomas cargados.</p>
                    <a href="@Url.Action("Nuevo", "Idioma")" class="btn btn-primary btn-xl page-scroll wow fadeInUp">Completar Idioma <i class="fa fa-globe"></i></a>
                }
                <hr class="primary">
            </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="eliminarIdioma" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header bg-danger">
                        <h5 class="modal-title" id="elimiarNIvel"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h6 id="eliminarDescripcion"></h6>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <p class="btn btn-lg btn-danger"><a href="" style="color:white; font-weight:bold" id="formularioEliminar">Eliminar</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $("td#eliminar").click(function () {
            var id = $(this).attr("data-id");
            var descripcion = $(this).attr("data-Descripcion");

            $("#id").val(id);
            $("#formularioEliminar").attr('href', '@Url.Action("Eliminar", "Idioma")' + '/' + id);
            $("#eliminarDescripcion").html("¿Está Seguro En Eliminar " + "<span class='text-danger text-center'>" + descripcion + "</span> ?");
        });
    </script>
</section>

CV.Web/Views/Idioma/Nuevo.cshtml
@model IdiomaDTO
@{
    ViewBag.Title = "Nuevo";
}

<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-9 col-sm-9 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "Idioma")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
            </div>
            <hr class="primary" />
            <h2>Completar Idioma</h2>

            <form method="post" action="@Url.Action("Nuevo", "Idioma")">
                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                <div class="col-sm-9 form-group">
                    <label for="Descripcion">Descripción:</label>
                    @Html.TextBoxFor(x => x.Descripcion, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(x => x.Descripcion)


                    @if (ViewBag.ObjUsuario != null)
                    {
                        <input type="hidden" value="@ViewBag.ObjUsuario.UsuarioId" name="UsuarioId" />
                    }
                </div>
                <div class="col-sm-9 form-group">
                    <label for="NivelEscrito">Nivel Escrito:</label>
                    @Html.DropDownListFor(x => x.NivelEscrito, new SelectList(new string[] { "--- Selecionar Nivel ---", "Bajo", "Intermedio", "Alto" }), new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.NivelEscrito)
                </div>

                <div class="col-sm-9 form-group">
                    <label for="NivelOral">Nivel Oral:</label>
                    @Html.DropDownListFor(x => x.NivelOral, new SelectList(new string[] { "--- Selecionar Nivel ---", "Bajo", "Intermedio", "Alto" }), new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.NivelOral)
                </div>

                <div class="col-sm-6 form-group">
                    <button type="submit" class="btn btn-success btn-lg">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="primary" />