CV.Web/Controllers/ImagenController.cs
using CV.Entidades;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Net.Http.Formatting;
using CV.Web.Models.ViewModels;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Drawing2D;
using System.IO;
using log4net;

namespace CV.Web.Controllers
{
    public class ImagenController : Controller
    {
        ImageViewModel img = new ImageViewModel();

        private static readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                #region Obtengo el ID del usuario
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }
                #endregion

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Imagen").Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var listado = JsonConvert.DeserializeObject<List<ImagenDTO>>(resultString);
                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultado = listado.FirstOrDefault(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);
                        return View(resultado);
                    }
                    else
                    {
                        return View(listado);
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            try
            {
                #region Obtengo el ID del usuario
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }
                #endregion

                #region ViewModel para subir la imagen al servidor
                var model = new ImageViewModel
                {
                    foto = img.foto
                };

                ViewBag.Img = model;
                #endregion
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(ImagenDTO imagen, ImageViewModel img)
        {
            try
            {
                var random = new Random().Next(0, 100);
                string extension = Path.GetExtension(img.foto.FileName);
                bool extensionOk = ValidarExtension(extension);

                if (extensionOk == true)
                {
                    Redimensionar(img.foto.InputStream);
                    string ImageName = System.IO.Path.GetFileName(img.foto.FileName);
                    imagen.Nombre = random + ImageName;

                    HttpClient clienteHttp = new HttpClient();
                    clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                    var request = clienteHttp.PostAsync("api/Imagen", imagen, new JsonMediaTypeFormatter()).Result;

                    if (request.IsSuccessStatusCode)
                    {

                        string physicalPath = Server.MapPath("~/Content/Imagenes/Upload/" + ImageName);

                        img.foto.SaveAs(physicalPath);

                        var resultString = request.Content.ReadAsStringAsync().Result;
                        var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                        if (correcto)
                        {
                            return RedirectToAction("index");
                        }

                        return View(imagen);
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Actualizar(int id)
        {
            try
            {
                #region Obtengo el ID del usuario
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }
                #endregion


                #region ViewModel para subir la imagen al servidor
                var model = new ImageViewModel
                {
                    foto = img.foto
                };

                ViewBag.Img = model;
                #endregion

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Imagen/" + id).Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<ImagenDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Actualizar(ImagenDTO imagen, ImageViewModel img)
        {
            try
            {
                var random = new Random().Next(0, 100);
                string extension = Path.GetExtension(img.foto.FileName);
                bool extensionOk = ValidarExtension(extension);

                if (extensionOk == true)
                {
                    Image imagenRedimensionada = Redimensionar(img.foto.InputStream);
                    string ImageName = System.IO.Path.GetFileName(img.foto.FileName);
                    ImageName = random + ImageName;
                    imagen.Nombre = ImageName;

                    HttpClient clienteHttp = new HttpClient();
                    clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                    var request = clienteHttp.PutAsync("api/Imagen/", imagen, new JsonMediaTypeFormatter()).Result;

                    if (request.IsSuccessStatusCode)
                    {

                        #region Elimina la imagen del servidor
                        var peticion = clienteHttp.DeleteAsync("api/Imagen/" + imagen.ImagenId).Result;

                        if (peticion.IsSuccessStatusCode)
                        {
                            var resultadoStringEliminar = request.Content.ReadAsStringAsync().Result;
                            var listado = JsonConvert.DeserializeObject<List<ImagenDTO>>(resultadoStringEliminar);

                            if (ViewBag.ObjUsuario != null)
                            {
                                var resultado = listado.FirstOrDefault(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);
                                System.IO.File.Delete(resultado.Nombre);
                            }
                        }
                        #endregion


                        #region Carga la nueva imagen
                        string physicalPath = Server.MapPath("~/Content/Imagenes/Upload/" + ImageName);
                        img.foto.SaveAs(physicalPath);
                        #endregion

                        var resultString = request.Content.ReadAsStringAsync().Result;
                        var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                        if (correcto)
                        {
                            return RedirectToAction("index");
                        }
                    }

                    return View(imagen);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.DeleteAsync("api/Imagen/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {

                    #region Elimina la imagen del servidor

                    if (request.IsSuccessStatusCode)
                    {
                        var resultadoString = request.Content.ReadAsStringAsync().Result;
                        var listado = JsonConvert.DeserializeObject<List<ImagenDTO>>(resultadoString);

                        if (ViewBag.ObjUsuario != null)
                        {
                            var resultado = listado.FirstOrDefault(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);
                            System.IO.File.Delete(resultado.Nombre);
                        }
                    }

CV.Web/Controllers/PDFController.cs
using CV.Entidades;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Net.Http.Formatting;
using log4net;

namespace CV.Web.Controllers
{
    public class PDFController : Controller
    {
        private static readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                #region Obtengo el ID del usuario
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }
                #endregion

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                #region Invocamos Datos Personales
                var requestDatosPersonales = clienteHttp.GetAsync("api/DatosPersonales").Result;
                if (requestDatosPersonales.IsSuccessStatusCode)
                {
                    var resultStringDatosPersonales = requestDatosPersonales.Content.ReadAsStringAsync().Result;
                    var listadoDatosPersonales = JsonConvert.DeserializeObject<List<DatosPersonalesDTO>>(resultStringDatosPersonales);

                    if (ViewBag.ObjUsuario != null)
                    {
                        var DatosPersonales = listadoDatosPersonales.FirstOrDefault(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);
                        ViewBag.DatosPersonales = DatosPersonales;
                    }
                }
                #endregion

                #region Invocamos Educación
                var requestEducacion = clienteHttp.GetAsync("api/Educacion").Result;

                if (requestEducacion.IsSuccessStatusCode)
                {
                    var resultStringEducacion = requestEducacion.Content.ReadAsStringAsync().Result;
                    var listadoEducacion = JsonConvert.DeserializeObject<List<EducacionDTO>>(resultStringEducacion);

                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultadorequestEducacion = listadoEducacion.Where(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);
                        ViewBag.requestEducacion = resultadorequestEducacion;
                    }
                }
                #endregion

                #region Invocamos Experiencia Laboral
                var requestExperienciaLaboral = clienteHttp.GetAsync("api/ExperienciaLaboral").Result;

                if (requestExperienciaLaboral.IsSuccessStatusCode)
                {
                    var resultStringExperienciaLaboral = requestExperienciaLaboral.Content.ReadAsStringAsync().Result;
                    var listadoExperienciaLaboral = JsonConvert.DeserializeObject<List<ExperienciaLaboralDTO>>(resultStringExperienciaLaboral);
                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultadoExperienciaLaboral = listadoExperienciaLaboral.Where(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);
                        ViewBag.ExperienciaLaboral = resultadoExperienciaLaboral;
                    }

                }
                #endregion

                #region Invocamos Idioma
                var requestIdioma = clienteHttp.GetAsync("api/Idioma").Result;

                if (requestIdioma.IsSuccessStatusCode)
                {
                    var resultStringIdioma = requestIdioma.Content.ReadAsStringAsync().Result;
                    var listadoIdioma = JsonConvert.DeserializeObject<List<IdiomaDTO>>(resultStringIdioma);
                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultadoIdioma = listadoIdioma.Where(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);
                        ViewBag.Idioma = resultadoIdioma;
                    }
                }
                #endregion

                #region Invocamos Conocimientos
                var requestConocimiento = clienteHttp.GetAsync("api/Conocimiento").Result;

                if (requestConocimiento.IsSuccessStatusCode)
                {
                    var resultStringConocimiento = requestConocimiento.Content.ReadAsStringAsync().Result;
                    var listadoConocimiento = JsonConvert.DeserializeObject<List<ConocimientoDTO>>(resultStringConocimiento);
                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultadoConocimiento = listadoConocimiento.Where(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);
                        ViewBag.Conocimiento = resultadoConocimiento;
                    }
                }
                #endregion

                #region Invocamos Objetivo
                var requestObjetivo = clienteHttp.GetAsync("api/Objetivo").Result;

                if (requestObjetivo.IsSuccessStatusCode)
                {
                    var resultStringObjetivo = requestObjetivo.Content.ReadAsStringAsync().Result;
                    var listadoObjetivo = JsonConvert.DeserializeObject<List<ObjetivoDTO>>(resultStringObjetivo);
                    var resultadoObjetivo = listadoObjetivo.FirstOrDefault(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);

                    ViewBag.Objetivo = resultadoObjetivo;
                }
                #endregion

                #region Invocamos la imagen
                var requestImagen = clienteHttp.GetAsync("api/Imagen").Result;

                if (requestImagen.IsSuccessStatusCode)
                {
                    var resultStringImagen = requestImagen.Content.ReadAsStringAsync().Result;
                    var listadoImagen = JsonConvert.DeserializeObject<List<ImagenDTO>>(resultStringImagen);
                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultadoImagen = listadoImagen.FirstOrDefault(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);
                        ViewBag.Imagen = resultadoImagen;
                    }
                }
                #endregion

                return View();
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }
    }
}

CV.Web/Views/Imagen/Actualizar.cshtml
@model ImagenDTO

<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-9 col-sm-9 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "Imagen")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
            </div>

            <h2>Editar Imagen</h2>

            <div class="col-sm-9 form-group">
                <img class="figure-img" src="~/Content/Imagenes/Upload/@Model.Nombre" alt="@Model.Nombre" title="@Model.Nombre" />
            </div>

            <form method="post" action="@Url.Action("Actualizar", "Imagen")" enctype="multipart/form-data">
                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.ImagenId)
                
                <div class="col-sm-9 form-group">
                    @Html.HiddenFor(x => x.Nombre, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(x => x.Nombre)
                </div>

                <div class="col-sm-9 form-group">
                    @if (ViewBag.ObjUsuario != null)
                    {
                        <input type="hidden" value="@ViewBag.ObjUsuario.UsuarioId" name="UsuarioId" />
                    }
                </div>
                
                <div class="col-sm-9 form-group">
                    <label for="foto">Foto:</label>
                    <input type="file" id="foto" value="@ViewBag.Img.foto" class="form-control-file" name="foto" />
                </div>

                <div class="col-sm-6 form-group">
                    <button type="submit" class="btn btn-success btn-lg">Editar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="primary" />

CV.Web/Views/Imagen/Detalle.cshtml
@model ImagenDTO

<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-12 col-sm-12 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "Imagen")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
                <a href="@Url.Action("Actualizar", "Imagen", new { id = Model.ImagenId})"><p class="btn btn-outline-dark btn-lg text-uppercase"><i class="fa fa-edit"></i> Editar</p></a>
            </div>

            @if (ViewBag.ObjUsuario != null)
            {
                <input type="hidden" value="@ViewBag.ObjUsuario.UsuarioId" name="UsuarioId" />
            }
            @Html.HiddenFor(x => x.ImagenId)

            <div class="card col-lg-12 col-sm-12">
                <div class="card-header text-center">
                    <img class="figure-img" src="~/Content/Imagenes/Upload/@Model.Nombre" alt="@Model.Nombre" title="@Model.Nombre" />
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><i class="fa fa-info-circle fa-2x"></i> Nombre de la imagen: @Model.Nombre</li>
                </ul>
            </div>
        </div>
    </div>
</div>

CV.Web/Views/Imagen/Index.cshtml
@model ImagenDTO
@{
    ViewBag.Title = "Index";
}

<section id="two" class="bg-alt">

    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-xs-center">
                @if (ViewBag.ObjUsuario != null)
                {
                    <h2>Bienvenido <span class="text-success">@ViewBag.ObjUsuario.UsuarioNombre</span>, Empecemos a completar el CV.</h2>
                }

                <h3 class="m-t-0 text-primary">Impulsá tu carrera profesional</h3>
                <h4>Imagen</h4>
                @if (Model != null)
                {
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Nombres</th>
                                <th>Ver</th>
                                <th>Editar</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><img class="figure-img" src="~/Content/Imagenes/Upload/@Model.Nombre" alt="@Model.Nombre" title="@Model.Nombre" /></td>
                                <td><a href="@Url.Action("Detalle", "Imagen", new { id = Model.ImagenId})"><i class="fa fa-eye fa-2x"></i></a></td>
                                <td><a href="@Url.Action("Actualizar", "Imagen", new { id = Model.ImagenId})"><i class="fa fa-edit fa-2x text-success"></i></a></td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="@Url.Action("Index", "PDF")" class="btn btn-primary btn-xl page-scroll wow fadeInUp">Ver CV <i class="fa fa-file-pdf-o"></i></a>
                }
                else
                {
                    <p class="text-capitalize alert alert-warning text-center">No tiene una imagen cargada.</p>
                    <hr class="primary">
                    <p><a href="@Url.Action("Nuevo", "Imagen")" class="btn btn-primary btn-xl page-scroll wow fadeInUp">Cargar Imagen <i class="fa fa-image"></i></a></p>
                }
                <hr class="primary">
            </div>
        </div>
    </div>

</section>

CV.Web/Views/Imagen/Nuevo.cshtml
@{
    @model ImagenDTO
}
<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-9 col-sm-9 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "Imagen")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
            </div>
            <hr class="primary" />
            <h2>Cargar Imagen</h2>

            <form method="post" action="@Url.Action("Nuevo", "Imagen")" enctype="multipart/form-data">
                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                <div class="col-sm-9 form-group">
                    @Html.HiddenFor(x => x.Nombre, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(x => x.Nombre)
                </div>

                <div class="col-sm-9 form-group">
                    <label for="foto">Foto:</label>
                    <input type="file" id="foto" value="@ViewBag.Img.foto" class="form-control-file" name="foto" />
                </div>
                
                <div class="col-sm-9 form-group">    
                    
                    @if (ViewBag.ObjUsuario != null)
                    {
                        <input type="hidden" value="@ViewBag.ObjUsuario.UsuarioId" name="UsuarioId" />
                    }
                </div>
                
                <div class="col-sm-6 form-group">
                    <button type="submit" class="btn btn-success btn-lg">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="primary" />