CV.Web/Controllers/ConocimientoController.cs
using CV.Entidades;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Net.Http.Formatting;
using log4net;

namespace CV.Web.Controllers
{
    public class ConocimientoController : Controller
    {
        private static readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Conocimiento").Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var listado = JsonConvert.DeserializeObject<List<ConocimientoDTO>>(resultString);
                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultado = listado.Where(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId).OrderByDescending(x => x.ConocimientoId);
                        return View(resultado);
                    }
                    else
                    {
                        return View(listado);
                    }
                }

                return View();
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                return View();
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(ConocimientoDTO conocimiento)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PostAsync("api/Conocimiento", conocimiento, new JsonMediaTypeFormatter()).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                    return View(conocimiento);
                }

                return View(conocimiento);
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Actualizar(int id)
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Conocimiento/" + id).Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<ConocimientoDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Actualizar(ConocimientoDTO conocimiento)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PutAsync("api/Conocimiento/", conocimiento, new JsonMediaTypeFormatter()).Result;

            try
            {

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.DeleteAsync("api/Conocimiento/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Detalle(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.GetAsync("api/Conocimiento/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<ConocimientoDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }
    }
}

CV.Web/Controllers/ObjetivoController.cs
using CV.Entidades;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Net.Http.Formatting;
using log4net;

namespace CV.Web.Controllers
{
    public class ObjetivoController : Controller
    {
        private static readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Objetivo").Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var listado = JsonConvert.DeserializeObject<List<ObjetivoDTO>>(resultString);
                    var resultado = listado.FirstOrDefault(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId);

                    return View(resultado);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                return View();
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(ObjetivoDTO objetivo)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PostAsync("api/Objetivo", objetivo, new JsonMediaTypeFormatter()).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                    return View(objetivo);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View(objetivo);
        }

        [HttpGet]
        public ActionResult Actualizar(int id)
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Objetivo/" + id).Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<ObjetivoDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Actualizar(ObjetivoDTO objetivo)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PutAsync("api/Objetivo/", objetivo, new JsonMediaTypeFormatter()).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.DeleteAsync("api/Objetivo/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Detalle(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.GetAsync("api/Objetivo/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<ObjetivoDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }
    }
}

CV.Web/Views/Objetivo/Actualizar.cshtml
@model ObjetivoDTO

<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-9 col-sm-9 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "Objetivo")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
            </div>

            <h2>Editar Perfil Profesional</h2>

            <form method="post" action="@Url.Action("Actualizar", "Objetivo")">
                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                @if (ViewBag.ObjUsuario != null)
                {
                    <input type="hidden" value="@ViewBag.ObjUsuario.UsuarioId" name="UsuarioId" />
                }
                @Html.HiddenFor(x => x.ObjetivoId)
                <div class="col-sm-9 form-group">
                    <label for="Descripcion">Descripción: </label>
                    @Html.TextAreaFor(x => x.Descripcion, new { @class = "form-control", @required = "required", @cols = 40, @rows = 10 })
                    @Html.ValidationMessageFor(x => x.Descripcion)

                </div>
                
                <div class="col-sm-6 form-group">
                    <button type="submit" class="btn btn-success btn-lg">Editar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="primary" />

CV.Web/Views/Objetivo/Detalle.cshtml
@model ObjetivoDTO

<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-12 col-sm-12 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "Objetivo")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
                <a href="@Url.Action("Actualizar", "Objetivo", new { id = Model.ObjetivoId})"><p class="btn btn-outline-dark btn-lg text-uppercase"><i class="fa fa-edit"></i> Editar</p></a>
            </div>

            <div class="card col-lg-12 col-sm-12">
                <div class="card-header text-center">
                    <i class="fa fa-graduation-cap fa-2x text-primary"></i> Perfil Profesional: @Model.Descripcion
                </div>
            </div>
        </div>
    </div>
</div>

CV.Web/Views/Objetivo/Index.cshtml
@model ObjetivoDTO
@{
    ViewBag.Title = "Index";
}

<section id="two" class="bg-alt">

    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-xs-center">
                @if (ViewBag.ObjUsuario != null)
                {
                    <h2><span class="text-success">@ViewBag.ObjUsuario.UsuarioNombre</span> Continuemos completando el CV.</h2>
                }

                <h3 class="m-t-0 text-primary">Impulsá tu carrera profesional</h3>
                <a href="@Url.Action("Index", "Conocimiento")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
                <h4>Perfil Profesional</h4>
                @if (Model != null)
                {
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Descripción</th>
                                <th>Ver</th>
                                <th>Editar</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>@Model.Descripcion</td>
                                <td><a href="@Url.Action("Detalle", "Objetivo", new { id = Model.ObjetivoId})"><i class="fa fa-eye fa-2x"></i></a></td>
                                <td><a href="@Url.Action("Actualizar", "Objetivo", new { id = Model.ObjetivoId })"><i class="fa fa-edit fa-2x text-success"></i></a></td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="@Url.Action("Index", "imagen")" class="btn btn-primary btn-xl page-scroll wow fadeInUp">Cargar imagen <i class="fa fa-image"></i></a>
                }
                else
                {
                    <p class="text-capitalize">No hay ningún item cargado.</p>
                    <a href="@Url.Action("Nuevo", "Objetivo")" class="btn btn-primary btn-xl page-scroll wow fadeInUp">Completar Perfil Profesional <i class="fa fa-graduation-cap"></i></a>
                }
                <hr class="primary">
            </div>
        </div>
        
    </div>
</section>

CV.Web/Views/Objetivo/Nuevo.cshtml
@model ObjetivoDTO
@{
    ViewBag.Title = "Nuevo";
}

<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-9 col-sm-9 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "Objetivo")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
            </div>
            <hr class="primary" />
            <h2>Completar Objetivo</h2>

            <form method="post" action="@Url.Action("Nuevo", "Objetivo")">
                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                <div class="col-sm-9 form-group">
                    <label for="Descripcion">Descripción:</label>
                    @Html.TextAreaFor(x => x.Descripcion, new { @class = "form-control", @required = "required", @cols = 40, @rows = 10 })
                    @Html.ValidationMessageFor(x => x.Descripcion)


                    @if (ViewBag.ObjUsuario != null)
                    {
                        <input type="hidden" value="@ViewBag.ObjUsuario.UsuarioId" name="UsuarioId" />
                    }
                </div>
                
                <div class="col-sm-6 form-group">
                    <button type="submit" class="btn btn-success btn-lg">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="primary" />