CV.Web/Controllers/ExperienciaLaboralController.cs
using CV.Entidades;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Net.Http.Formatting;
using log4net;

namespace CV.Web.Controllers
{
    public class ExperienciaLaboralController : Controller
    {
        private static readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/ExperienciaLaboral").Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var listado = JsonConvert.DeserializeObject<List<ExperienciaLaboralDTO>>(resultString);
                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultado = listado.Where(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId).OrderByDescending(x => x.ExperienciaLaboralId);
                        return View(resultado);
                    }
                    else
                    {
                        return View(listado);
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                return View();
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(ExperienciaLaboralDTO experiencia)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PostAsync("api/ExperienciaLaboral", experiencia, new JsonMediaTypeFormatter()).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                    return View(experiencia);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View(experiencia);
        }

        [HttpGet]
        public ActionResult Actualizar(int id)
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/ExperienciaLaboral/" + id).Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<ExperienciaLaboralDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Actualizar(ExperienciaLaboralDTO experiencia)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PutAsync("api/ExperienciaLaboral/", experiencia, new JsonMediaTypeFormatter()).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.DeleteAsync("api/ExperienciaLaboral/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Detalle(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.GetAsync("api/ExperienciaLaboral/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<ExperienciaLaboralDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }
    }
}

CV.Web/Controllers/IdiomaController.cs
using CV.Entidades;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Net.Http.Formatting;
using log4net;

namespace CV.Web.Controllers
{
    public class IdiomaController : Controller
    {
        private static readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Idioma").Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var listado = JsonConvert.DeserializeObject<List<IdiomaDTO>>(resultString);
                    if (ViewBag.ObjUsuario != null)
                    {
                        var resultado = listado.Where(x => x.UsuarioId == ViewBag.ObjUsuario.UsuarioId).OrderByDescending(x => x.IdiomaId);
                        return View(resultado);
                    }
                    else
                    {
                        return View(listado);
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                return View();
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(IdiomaDTO idioma)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PostAsync("api/Idioma", idioma, new JsonMediaTypeFormatter()).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                    return View(idioma);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View(idioma);
        }

        [HttpGet]
        public ActionResult Actualizar(int id)
        {
            try
            {
                if (Session["Usuario"] == null)
                {
                    Session["Usuario"] = null;
                }
                else
                {
                    var objUsuario = Session["Usuario"];
                    ViewBag.ObjUsuario = objUsuario;
                }

                HttpClient clienteHttp = new HttpClient();
                clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

                var request = clienteHttp.GetAsync("api/Idioma/" + id).Result;

                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<IdiomaDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Actualizar(IdiomaDTO idioma)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.PutAsync("api/Idioma/", idioma, new JsonMediaTypeFormatter()).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.DeleteAsync("api/Idioma/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var correcto = JsonConvert.DeserializeObject<bool>(resultString);

                    if (correcto)
                    {
                        return RedirectToAction("index");
                    }
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Detalle(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://localhost:5476/");

            var request = clienteHttp.GetAsync("api/Idioma/" + id).Result;

            try
            {
                if (request.IsSuccessStatusCode)
                {
                    var resultString = request.Content.ReadAsStringAsync().Result;
                    var informacion = JsonConvert.DeserializeObject<IdiomaDTO>(resultString);

                    return View(informacion);
                }
            }
            catch (Exception ex)
            {
                log.ErrorFormat("Error: {0}{1}", ex.StackTrace, ex.Message);
            }

            return View();
        }
    }
}

CV.Web/Views/ExperienciaLaboral/Actualizar.cshtml
@model ExperienciaLaboralDTO

<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-9 col-sm-9 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "ExperienciaLaboral")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
            </div>

            <h2>Editar Experiencia Laboral</h2>

            <form method="post" action="@Url.Action("Actualizar", "ExperienciaLaboral")">
                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.ExperienciaLaboralId)
                <div class="col-sm-9 form-group">
                    <label for="Puesto">Puesto: </label>
                    @Html.TextBoxFor(x => x.Puesto, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(x => x.Puesto)


                    @if (ViewBag.ObjUsuario != null)
                    {
                        <input type="hidden" value="@ViewBag.ObjUsuario.UsuarioId" name="UsuarioId" />
                    }
                </div>
                <div class="col-sm-9 form-group">
                    <label for="Descripcion">Descripción:</label>
                    @Html.TextAreaFor(x => x.Descripcion, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(x => x.Descripcion)
                </div>

                <div class="col-sm-6 form-group">
                    <label for="FechaDesde">Fecha Desde:</label>
                    @Html.TextBoxFor(x => x.FechaDesde, "{0:yyyy-MM-dd}", new { @class = "form-control", @required = "required", @type = "date" })
                    @Html.ValidationMessageFor(x => x.FechaDesde)
                </div>
                <div class="col-sm-6 form-group">
                    <label for="nacionalidad">Fecha Hasta:</label>
                    @Html.TextBoxFor(x => x.FechaHasta, new { @class = "form-control", @type = "date" })
                </div>
                <div class="col-sm-6 form-group">
                    @Html.RadioButtonFor(x => x.Actualidad, true, new { @class = "form-check-input" })
                    <label for="Actualidad" class="form-check-label">Actualidad</label>
                </div>
                <div class="col-sm-9 form-group">
                    <label for="ReferenciaNombre">Referencia Laboral:</label>
                    @Html.TextBoxFor(x => x.ReferenciaNombre, new { @class = "form-control" })
                </div>
                <div class="col-sm-9 form-group">
                    <label for="dom">Referencia Teléfono:</label>
                    @Html.TextBoxFor(x => x.ReferenciaTelefono, new { @class = "form-control" })
                </div>
                
                <div class="col-sm-6 form-group">
                    <button type="submit" class="btn btn-success btn-lg">Editar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="primary" />

CV.Web/Views/ExperienciaLaboral/Detalle.cshtml
@model ExperienciaLaboralDTO

<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-12 col-sm-12 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "ExperienciaLaboral")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
                <a href="@Url.Action("Actualizar", "ExperienciaLaboral", new { id = Model.ExperienciaLaboralId})"><p class="btn btn-outline-dark btn-lg text-uppercase"><i class="fa fa-edit"></i> Editar</p></a>
            </div>

            @if (ViewBag.ObjUsuario != null)
            {
                <input type="hidden" value="@ViewBag.ObjUsuario.UsuarioId" name="UsuarioId" />
            }
            @Html.HiddenFor(x => x.ExperienciaLaboralId)

            <div class="card col-lg-12 col-sm-12">
                <div class="card-header text-center">
                    @Model.Puesto
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><i class="fa fa-building fa-2x"></i> Descripción: @Model.Descripcion</li>
                    <li class="list-group-item"><i class="fa fa-calendar-o fa-2x"></i> Fecha Desde: @Model.FechaDesde.ToShortDateString()</li>
                    @if (Model.FechaHasta.HasValue || Model.FechaHasta != null)
                    {
                        <li class="list-group-item"><i class="fa fa-calendar-o fa-2x"></i> Fecha Hasta: @Model.FechaHasta</li>
                    }
                    @if (Model.Actualidad == true)
                    {
                        <li class="list-group-item"><i class="fa fa-calendar-o fa-2x"></i> Hasta la actualidad</li>
                    }
                    <li class="list-group-item"><i class="fa fa-user-circle fa-2x"></i> Referencia: @Model.ReferenciaNombre</li>
                    <li class="list-group-item"><i class="fa fa-phone fa-2x"></i> Referencia Teléfono: @Model.ReferenciaTelefono</li></ul>
            </div>
        </div>
    </div>
</div>

CV.Web/Views/ExperienciaLaboral/Index.cshtml
@model IEnumerable<ExperienciaLaboralDTO>
@{
    ViewBag.Title = "Index";
}

<section id="two" class="bg-alt">

    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-xs-center">
                @if (ViewBag.ObjUsuario != null)
                {
                    <h2>Bienvenido <span class="text-success">@ViewBag.ObjUsuario.UsuarioNombre</span>, Continuemos completando el CV.</h2>
                }

                <h3 class="m-t-0 text-primary">Impulsá tu carrera profesional</h3>
                <div class="col-sm-12">
                    <a href="@Url.Action("Index", "Educacion")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
                </div>
                <h4>Experiencia Laboral</h4>
                @if (Model != null)
                {
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Puesto</th>
                                <th>Descripción</th>
                                <th>Ver</th>
                                <th>Editar</th>
                                <th>Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach (var datos in Model)
                        {
                            <tr>
                                <td>@datos.Puesto</td>
                                <td>@datos.Descripcion</td>
                                <td><a href="@Url.Action("Detalle", "ExperienciaLaboral", new { id = @datos.ExperienciaLaboralId })"><i class="fa fa-eye fa-2x"></i></a></td>
                                <td><a href="@Url.Action("Actualizar", "ExperienciaLaboral", new { id = @datos.ExperienciaLaboralId })"><i class="fa fa-edit fa-2x text-success"></i></a></td>
                                <td style="cursor:pointer" id="eliminar" data-descripcion="@datos.Descripcion" data-id="@datos.ExperienciaLaboralId" data-puesto="@datos.Puesto" data-toggle="modal" data-target="#eliminarExperiencia"><i class="fa fa-trash fa-2x text-danger"></i></td>
                            </tr>
                        }
                        </tbody>
                    </table>
                    <a href="@Url.Action("Nuevo", "ExperienciaLaboral")" class="btn btn-dark btn-xl page-scroll wow fadeInUp">Completar Experiencia Laboral <i class="fa fa-user-plus"></i></a>
                    <a href="@Url.Action("Index", "Idioma")" class="btn btn-primary btn-xl page-scroll wow fadeInUp">Completar Idioma <i class="fa fa-globe"></i></a>
                }
                else
                {
                    <p class="text-capitalize text-primary"><i class="fa fa-warning fa-2x"></i> No hay Item cargados en Experiencia Laboral</p>
                    <a href="@Url.Action("Nuevo", "ExperienciaLaboral")" class="btn btn-primary btn-xl page-scroll wow fadeInUp">Completar Experiencia Laboral <i class="fa fa-user-plus"></i></a>
                }
                <hr class="primary">
            </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="eliminarExperiencia" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header bg-danger">
                        <h5 class="modal-title" id="eliminarpuesto"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h6 id="eliminarDescripcion"></h6>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <p class="btn btn-lg btn-danger"><a href="" style="color:white; font-weight:bold" id="formularioEliminar">Eliminar</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $("td#eliminar").click(function () {
            var id = $(this).attr("data-id");
            var puesto = $(this).attr("data-puesto");
            var descripcion = $(this).attr("data-descripcion");

            $("#id").val(id);
            $("#formularioEliminar").attr('href', '@Url.Action("Eliminar", "ExperienciaLaboral")' + '/' + id);
            $("#eliminarpuesto").html("Descripción: " + descripcion);
            $("#eliminarDescripcion").html("¿Está Seguro En Eliminar " + "<span class='text-danger text-center'>" + puesto + "</span> ?");
        });
    </script>
</section>

CV.Web/Views/ExperienciaLaboral/Nuevo.cshtml
@model ExperienciaLaboralDTO
@{
    ViewBag.Title = "Completar Datos Personales";
}
<div class="container wow fadeInUp">
    <div class="row">

        <div class="col-lg-9 col-sm-9 text-capitalize">
            <div class="col-sm-12">
                <a href="@Url.Action("Index", "ExperienciaLaboral")"><p class="btn btn-lg btn-primary text-uppercase"><i class="fa fa-chevron-circle-left"></i> Volver</p></a>
            </div>
            <hr class="primary" />
            <h2>Completar Experiencia Laboral</h2>

            <form method="post" action="@Url.Action("Nuevo", "ExperienciaLaboral")">
                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                <div class="col-sm-9 form-group">
                    <label for="Puesto">Puesto:</label>
                    @Html.TextBoxFor(x => x.Puesto, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(x => x.Puesto)


                    @if (ViewBag.ObjUsuario != null)
                    {
                        <input type="hidden" value="@ViewBag.ObjUsuario.UsuarioId" name="UsuarioId" />
                    }
                </div>
                <div class="col-sm-9 form-group">
                    <label for="apellido">Descrición:</label>
                    @Html.TextAreaFor(x => x.Descripcion, new { @class = "form-control", @required = "required", rows = "6", cols = "10" })
                    @Html.ValidationMessageFor(x => x.Descripcion)
                </div>

                <div class="col-sm-6 form-group">
                    <label for="fechaNac">Fecha Desde:</label>
                    @Html.TextBoxFor(x => x.FechaDesde, new { @class = "form-control", @required = "required", @type = "date" })
                    @Html.ValidationMessageFor(x => x.FechaDesde)
                </div>
                <div class="col-sm-6 form-group">
                    <label for="FechaHasta">Fecha Hasta:</label>
                    @Html.TextBoxFor(x => x.FechaHasta, new { @class = "form-control", @required = "required", @type = "date" })
                    @Html.ValidationMessageFor(x => x.FechaHasta)
                </div>
                <div class="col-sm-9 form-group">
                    <label for="lugarNac">Referencia:</label>
                    @Html.TextBoxFor(x => x.ReferenciaNombre, new { @class = "form-control" })
                </div>
                <div class="col-sm-9 form-group">
                    <label for="dom">Referencia Teléfono:</label>
                    @Html.TextBoxFor(x => x.ReferenciaTelefono, new { @class = "form-control" })
                </div>

                <div class="col-sm-6 form-group">
                    <button type="submit" class="btn btn-success btn-lg">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="primary" />